openmeteo.base-url= "https://api.open-meteo.com/v1/forecast"


pekko {
  stdout-loglevel = "DEBUG"
  loglevel = "DEBUG"
  actor {
    default-dispatcher {
      executor = "thread-pool-executor"
      thread-pool-executor {
        fixed-pool-size = 2
      }
    }
  }
}